//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApp.modell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public int MedicineId { get; set; }
        public int Count { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Purchase_Date { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
